name: Code Format Check

on:
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Check formatting
      id: format-check
      run: dart format --set-exit-if-changed .
      continue-on-error: true

    - name: Check linting
      id: lint-check
      run: dart analyze --fatal-infos
      continue-on-error: true

    - name: Format code
      if: steps.format-check.outcome == 'failure'
      run: dart format .

    - name: Fix linting issues
      if: steps.lint-check.outcome == 'failure'
      run: dart fix --apply

    - name: Commit and push formatting and linting changes
      if: steps.format-check.outcome == 'failure' || steps.lint-check.outcome == 'failure'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "auto fix"
        git push
